[build]
  publish = "netlify_deployment/dist"
  command = "echo 'Building AI Financial Assistant API with all 6 agents...'"
  functions = "netlify_deployment/functions"

[build.environment]
  PYTHON_VERSION = "3.8"
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/orchestrator/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  external_node_modules = ["@netlify/functions"]
  node_bundler = "esbuild"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS" 