# Streamlit Cloud Secrets Configuration
# Add this to your Streamlit Cloud app secrets

ORCHESTRATOR_URL = "https://orch.netlify.app/api"
 
# Optional: Add other configurations here
# MISTRAL_API_KEY = "your_key_here" 