# Streamlit Secrets Configuration
# Copy this file to .streamlit/secrets.toml and add your API keys

# Mistral AI API Key for Language Agent
MISTRAL_API_KEY = "your_mistral_api_key_here"

# Optional: OpenAI API Key (if needed for other agents)
# OPENAI_API_KEY = "your_openai_api_key_here"

# Add other API keys as needed 