# Streamlit Cloud Secrets Configuration
# This file contains the configuration for Streamlit Cloud deployment

# API Configuration
ORCHESTRATOR_URL = "https://ai-financial-assistant-multi-agent.netlify.app/.netlify/functions/orchestrator"
DEPLOYMENT_MODE = "production"

# Optional: Add API keys if needed
# MISTRAL_API_KEY = "your-mistral-api-key-here"
# OPENAI_API_KEY = "your-openai-api-key-here"

# Add other API keys as needed 