# Streamlit Secrets Configuration
# ⚠️  IMPORTANT: Replace the placeholder values below with your actual API keys
# 
# For Streamlit Cloud deployment:
# 1. Go to your Streamlit Cloud app settings
# 2. Navigate to "Secrets" section  
# 3. Add these keys with your actual values:

# 🔑 REQUIRED: Mistral AI API Key for Language Agent
# Get your API key from: https://console.mistral.ai/
MISTRAL_API_KEY = "your_mistral_api_key_here"

# 🔑 OPTIONAL: OpenAI API Key (if using OpenAI features)
# Get your API key from: https://platform.openai.com/api-keys
# OPENAI_API_KEY = "your_openai_api_key_here"

# 📝 Instructions:
# 1. Never commit real API keys to Git
# 2. Use Streamlit Cloud secrets for production deployment
# 3. For local development, replace values above with real keys

# Add other API keys as needed

# Orchestrator API URL (will be your Netlify URL)
ORCHESTRATOR_URL = "https://your-netlify-site.netlify.app/api"

# Voice Agent URL (optional)
VOICE_AGENT_URL = "https://your-voice-service.netlify.app/api"

# Additional configuration
APP_NAME = "AI Financial Assistant"
DEPLOYMENT_ENV = "production" 