# Streamlit Secrets Configuration
# Copy this file to .streamlit/secrets.toml and add your API keys

# API Configuration
ORCHESTRATOR_URL = "https://ai-financial-assistant-multi-agent.netlify.app/api/process"
DEPLOYMENT_MODE = "local"

# Mistral AI API Key for Language Agent
MISTRAL_API_KEY = "NxdIH9V8xm8eldEGZrKvC1M1ziS1jHal"

# Optional: OpenAI API Key (if needed for other agents)
# OPENAI_API_KEY = "your-openai-api-key-here"

# Add other API keys as needed 