# Streamlit Secrets Configuration
# Copy this file to .streamlit/secrets.toml and add your API keys

# API Configuration
ORCHESTRATOR_URL = "https://orch.netlify.app/api"

# Mistral AI API Key for Language Agent
MISTRAL_API_KEY = "your-mistral-api-key-here"

# Optional: OpenAI API Key (if needed for other agents)
# OPENAI_API_KEY = "your-openai-api-key-here"

# Add other API keys as needed 