# Streamlit Secrets Configuration
# Copy this file to .streamlit/secrets.toml and add your API keys

# API Configuration
#ORCHESTRATOR_URL = "http://localhost:8011"
ORCHESTRATOR_URL = "https://ai-financial-assistant-multi-agent.netlify.app/.netlify/functions/orchestrator"
DEPLOYMENT_MODE = "local"

# Mistral AI API Key for Language Agent
MISTRAL_API_KEY = "your-mistral-api-key-here"

# Optional: OpenAI API Key (if needed for other agents)
# OPENAI_API_KEY = "your-openai-api-key-here"

# Add other API keys as needed 